// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/incident.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/incident.go -destination=internal/handler/mock_incident_service.go -package=handler
//

// Package handler is a generated GoMock package.
package handler

import (
	context "context"
	reflect "reflect"

	domain "github.com/jordan-lenchitz/ledger-grievance/go-app/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIncidentService is a mock of IncidentService interface.
type MockIncidentService struct {
	ctrl     *gomock.Controller
	recorder *MockIncidentServiceMockRecorder
	isgomock struct{}
}

// MockIncidentServiceMockRecorder is the mock recorder for MockIncidentService.
type MockIncidentServiceMockRecorder struct {
	mock *MockIncidentService
}

// NewMockIncidentService creates a new mock instance.
func NewMockIncidentService(ctrl *gomock.Controller) *MockIncidentService {
	mock := &MockIncidentService{ctrl: ctrl}
	mock.recorder = &MockIncidentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIncidentService) EXPECT() *MockIncidentServiceMockRecorder {
	return m.recorder
}

// ArchiveIncident mocks base method.
func (m *MockIncidentService) ArchiveIncident(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveIncident", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ArchiveIncident indicates an expected call of ArchiveIncident.
func (mr *MockIncidentServiceMockRecorder) ArchiveIncident(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveIncident", reflect.TypeOf((*MockIncidentService)(nil).ArchiveIncident), ctx, id)
}

// CreateIncident mocks base method.
func (m *MockIncidentService) CreateIncident(ctx context.Context, req domain.IncidentCreate) (*domain.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIncident", ctx, req)
	ret0, _ := ret[0].(*domain.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIncident indicates an expected call of CreateIncident.
func (mr *MockIncidentServiceMockRecorder) CreateIncident(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIncident", reflect.TypeOf((*MockIncidentService)(nil).CreateIncident), ctx, req)
}

// GetGopherWisdom mocks base method.
func (m *MockIncidentService) GetGopherWisdom(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGopherWisdom", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGopherWisdom indicates an expected call of GetGopherWisdom.
func (mr *MockIncidentServiceMockRecorder) GetGopherWisdom(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGopherWisdom", reflect.TypeOf((*MockIncidentService)(nil).GetGopherWisdom), ctx)
}

// GetIncident mocks base method.
func (m *MockIncidentService) GetIncident(ctx context.Context, id uint64) (*domain.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncident", ctx, id)
	ret0, _ := ret[0].(*domain.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncident indicates an expected call of GetIncident.
func (mr *MockIncidentServiceMockRecorder) GetIncident(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncident", reflect.TypeOf((*MockIncidentService)(nil).GetIncident), ctx, id)
}

// GetWholesomeBouquet mocks base method.
func (m *MockIncidentService) GetWholesomeBouquet(ctx context.Context) (*domain.WholesomeBouquet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWholesomeBouquet", ctx)
	ret0, _ := ret[0].(*domain.WholesomeBouquet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWholesomeBouquet indicates an expected call of GetWholesomeBouquet.
func (mr *MockIncidentServiceMockRecorder) GetWholesomeBouquet(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWholesomeBouquet", reflect.TypeOf((*MockIncidentService)(nil).GetWholesomeBouquet), ctx)
}

// GetWholesomeCompliment mocks base method.
func (m *MockIncidentService) GetWholesomeCompliment(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWholesomeCompliment", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWholesomeCompliment indicates an expected call of GetWholesomeCompliment.
func (mr *MockIncidentServiceMockRecorder) GetWholesomeCompliment(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWholesomeCompliment", reflect.TypeOf((*MockIncidentService)(nil).GetWholesomeCompliment), ctx)
}

// ListIncidents mocks base method.
func (m *MockIncidentService) ListIncidents(ctx context.Context, params domain.ListParams) (domain.ListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIncidents", ctx, params)
	ret0, _ := ret[0].(domain.ListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIncidents indicates an expected call of ListIncidents.
func (mr *MockIncidentServiceMockRecorder) ListIncidents(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIncidents", reflect.TypeOf((*MockIncidentService)(nil).ListIncidents), ctx, params)
}

// PatchIncident mocks base method.
func (m *MockIncidentService) PatchIncident(ctx context.Context, id uint64, patch domain.IncidentPatch) (*domain.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchIncident", ctx, id, patch)
	ret0, _ := ret[0].(*domain.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PatchIncident indicates an expected call of PatchIncident.
func (mr *MockIncidentServiceMockRecorder) PatchIncident(ctx, id, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchIncident", reflect.TypeOf((*MockIncidentService)(nil).PatchIncident), ctx, id, patch)
}

// VouchIncident mocks base method.
func (m *MockIncidentService) VouchIncident(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VouchIncident", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// VouchIncident indicates an expected call of VouchIncident.
func (mr *MockIncidentServiceMockRecorder) VouchIncident(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VouchIncident", reflect.TypeOf((*MockIncidentService)(nil).VouchIncident), ctx, id)
}
