// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/pkgsite.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/pkgsite.go -destination=internal/service/mock_pkgsite_service.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	domain "github.com/jordan-lenchitz/ledger-grievance/go-app/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPkgsiteService is a mock of PkgsiteService interface.
type MockPkgsiteService struct {
	ctrl     *gomock.Controller
	recorder *MockPkgsiteServiceMockRecorder
	isgomock struct{}
}

// MockPkgsiteServiceMockRecorder is the mock recorder for MockPkgsiteService.
type MockPkgsiteServiceMockRecorder struct {
	mock *MockPkgsiteService
}

// NewMockPkgsiteService creates a new mock instance.
func NewMockPkgsiteService(ctrl *gomock.Controller) *MockPkgsiteService {
	mock := &MockPkgsiteService{ctrl: ctrl}
	mock.recorder = &MockPkgsiteServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPkgsiteService) EXPECT() *MockPkgsiteServiceMockRecorder {
	return m.recorder
}

// GetImportedBy mocks base method.
func (m *MockPkgsiteService) GetImportedBy(ctx context.Context, path string) (*domain.PackageImportedBy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImportedBy", ctx, path)
	ret0, _ := ret[0].(*domain.PackageImportedBy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImportedBy indicates an expected call of GetImportedBy.
func (mr *MockPkgsiteServiceMockRecorder) GetImportedBy(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImportedBy", reflect.TypeOf((*MockPkgsiteService)(nil).GetImportedBy), ctx, path)
}

// GetModule mocks base method.
func (m *MockPkgsiteService) GetModule(ctx context.Context, path string) (*domain.Module, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModule", ctx, path)
	ret0, _ := ret[0].(*domain.Module)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModule indicates an expected call of GetModule.
func (mr *MockPkgsiteServiceMockRecorder) GetModule(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModule", reflect.TypeOf((*MockPkgsiteService)(nil).GetModule), ctx, path)
}

// GetPackage mocks base method.
func (m *MockPkgsiteService) GetPackage(ctx context.Context, path string) (*domain.Package, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPackage", ctx, path)
	ret0, _ := ret[0].(*domain.Package)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPackage indicates an expected call of GetPackage.
func (mr *MockPkgsiteServiceMockRecorder) GetPackage(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPackage", reflect.TypeOf((*MockPkgsiteService)(nil).GetPackage), ctx, path)
}

// GetSymbols mocks base method.
func (m *MockPkgsiteService) GetSymbols(ctx context.Context, path string) (*domain.PackageSymbols, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSymbols", ctx, path)
	ret0, _ := ret[0].(*domain.PackageSymbols)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSymbols indicates an expected call of GetSymbols.
func (mr *MockPkgsiteServiceMockRecorder) GetSymbols(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSymbols", reflect.TypeOf((*MockPkgsiteService)(nil).GetSymbols), ctx, path)
}

// GetVersions mocks base method.
func (m *MockPkgsiteService) GetVersions(ctx context.Context, path string) (*domain.PaginatedResponse[domain.ModuleVersion], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersions", ctx, path)
	ret0, _ := ret[0].(*domain.PaginatedResponse[domain.ModuleVersion])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersions indicates an expected call of GetVersions.
func (mr *MockPkgsiteServiceMockRecorder) GetVersions(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersions", reflect.TypeOf((*MockPkgsiteService)(nil).GetVersions), ctx, path)
}

// GetVulns mocks base method.
func (m *MockPkgsiteService) GetVulns(ctx context.Context, path string) (*domain.PaginatedResponse[domain.Vulnerability], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVulns", ctx, path)
	ret0, _ := ret[0].(*domain.PaginatedResponse[domain.Vulnerability])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVulns indicates an expected call of GetVulns.
func (mr *MockPkgsiteServiceMockRecorder) GetVulns(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVulns", reflect.TypeOf((*MockPkgsiteService)(nil).GetVulns), ctx, path)
}

// Search mocks base method.
func (m *MockPkgsiteService) Search(ctx context.Context, query string) (*domain.PaginatedResponse[domain.SearchResult], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query)
	ret0, _ := ret[0].(*domain.PaginatedResponse[domain.SearchResult])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockPkgsiteServiceMockRecorder) Search(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockPkgsiteService)(nil).Search), ctx, query)
}
