// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/incident.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/incident.go -destination=internal/service/mock_incident_repository.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	domain "github.com/jordan-lenchitz/ledger-grievance/go-app/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIncidentRepository is a mock of IncidentRepository interface.
type MockIncidentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIncidentRepositoryMockRecorder
	isgomock struct{}
}

// MockIncidentRepositoryMockRecorder is the mock recorder for MockIncidentRepository.
type MockIncidentRepositoryMockRecorder struct {
	mock *MockIncidentRepository
}

// NewMockIncidentRepository creates a new mock instance.
func NewMockIncidentRepository(ctrl *gomock.Controller) *MockIncidentRepository {
	mock := &MockIncidentRepository{ctrl: ctrl}
	mock.recorder = &MockIncidentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIncidentRepository) EXPECT() *MockIncidentRepositoryMockRecorder {
	return m.recorder
}

// Archive mocks base method.
func (m *MockIncidentRepository) Archive(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Archive", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Archive indicates an expected call of Archive.
func (mr *MockIncidentRepositoryMockRecorder) Archive(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Archive", reflect.TypeOf((*MockIncidentRepository)(nil).Archive), ctx, id)
}

// Create mocks base method.
func (m *MockIncidentRepository) Create(ctx context.Context, inc *domain.Incident) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, inc)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIncidentRepositoryMockRecorder) Create(ctx, inc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIncidentRepository)(nil).Create), ctx, inc)
}

// GetByID mocks base method.
func (m *MockIncidentRepository) GetByID(ctx context.Context, id uint64) (*domain.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIncidentRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIncidentRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockIncidentRepository) List(ctx context.Context, params domain.ListParams) (domain.ListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].(domain.ListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIncidentRepositoryMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIncidentRepository)(nil).List), ctx, params)
}

// Update mocks base method.
func (m *MockIncidentRepository) Update(ctx context.Context, id uint64, patch domain.IncidentPatch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, patch)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIncidentRepositoryMockRecorder) Update(ctx, id, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIncidentRepository)(nil).Update), ctx, id, patch)
}
